### PR TITLE
fix lrem behavior

### PR DESCRIPTION
**Pull request by hoffmanc**
Ran into this while trying to switch to fakeredis for the resque tests.

### CODE REVIEW

**Comment by hoffmanc** [comment]
Can someone please review this pull request?  Thanks!

**Comment by hoffmanc** [comment]
bump

**Comment by hoffmanc** [comment]
Can someone please review this pull request? It's quite small.  Thanks!

**Comment by guilleiguaran** [comment]
thanks for this!!!

**Pull request merged**
