### PR TITLE
Fix sadd return when 0 or 1

### LINKED ISSUE #245: 0.8.0 returning bool instead of changed count when 0 or 1
Recently updated to 0.8.0 and we started seeing some spec failures.

It appears lines 18-23 were removed from `lib/fakeredis/command_executor.rb`
https://github.com/guilleiguaran/fakeredis/compare/v0.7.0...v0.8.0#diff-fdef1ab143affa7cb3400946214210edL18-L23 
Screen Shot 2020-05-13 at 12 02 23 PM

This is now making fakeredis return a bool value in (at least) the following situation:

Expected (tested with real redis):
```
[1] pry(main)> @redis.sadd("asdf", [1])
=> 1
[2] pry(main)> @redis.sadd("asdf", [2,3])
=> 2
[3] pry(main)> @redis.sadd("asdf", [3,4])
=> 1
[4] pry(main)> @redis.sadd("asdf", [1,2,3,4])
=> 0
```

Actual (tested in fakeredis 0.8.0):
```
[1] pry(main)> @redis.sadd("asdf", [1])
=> true
[2] pry(main)> @redis.sadd("asdf", [2,3])
=> 2
[3] pry(main)> @redis.sadd("asdf", [3,4])
=> true
[4] pry(main)> @redis.sadd("asdf", [1,2,3,4])
=> false
```

### PR DESCRIPTION
**Pull request by magicguitarist**
~~Reverts part of https://github.com/guilleiguaran/fakeredis/commit/871723bce5c546c7c846ea2b2c78dbe67216acce#diff-fdef1ab143affa7cb3400946214210ed~~

Fixes #245 

### Expected:
```
irb(main):001:0> require 'redis'
=> true
irb(main):002:0> @client = Redis.new
=> #<Redis client v4.2.2 for redis://127.0.0.1:6379/0>
irb(main):003:0> @client.sadd("realredis", 5)
=> true
irb(main):004:0> @client.sadd("realredis", 5)
=> false
irb(main):005:0> @client.sadd("realredis", [1])
=> 1
irb(main):006:0> @client.sadd("realredis", [1])
=> 0
irb(main):007:0> @client.sadd("realredis", [1,2])
=> 1
irb(main):008:0> @client.sadd("realredis", [3,4])
=> 2
```

### Before this PR
```
irb(main):001:0> require 'fakeredis'
=> true
irb(main):002:0> @client = Redis.new
=> #<Redis client v4.2.2 for redis://127.0.0.1:6379/0>
irb(main):003:0> @client.sadd("fakeredis", 5)
=> true
irb(main):004:0> @client.sadd("fakeredis", 5)
=> false
irb(main):005:0> @client.sadd("fakeredis", [1])
=> true
irb(main):006:0> @client.sadd("fakeredis", [1])
=> false
irb(main):007:0> @client.sadd("fakeredis", [1,2])
=> true
irb(main):008:0> @client.sadd("fakeredis", [3,4])
=> 2
```

### After this PR
```
irb(main):001:0> require 'fakeredis'
=> true
irb(main):002:0> @client = Redis.new
=> #<Redis client v4.2.2 for redis://127.0.0.1:6379/0>
irb(main):003:0> @client.sadd("fakeredis", 5)
=> true
irb(main):004:0> @client.sadd("fakeredis", 5)
=> false
irb(main):005:0> @client.sadd("fakeredis", [1])
=> 1
irb(main):006:0> @client.sadd("fakeredis", [1])
=> 0
irb(main):007:0> @client.sadd("fakeredis", [1,2])
=> 1
irb(main):008:0> @client.sadd("fakeredis", [3,4])
=> 2
```

### CODE REVIEW

**Comment by magicguitarist** [comment]
Specs failing on `ruby-head` due to ruby 3.0 being the latest version, which is causing dependency issues with some gems

**Comment by rocket-turtle** [comment]
Why do you change the write methode? I think this was removed for the redis dependency update.
Fix could be done in the `sadd` method as well or?

https://github.com/guilleiguaran/fakeredis/tree/v0.8.0/lib/redis/connection/memory.rb#L558
```
        # 0 = false, 1 = true, 2+ untouched
        return result == 1 if result < 2 && value.is_a?(Array)
```

**Comment by magicguitarist** [comment]
Good call, it does make more sense to put in into `sadd` in this case, will investigate and update this PR when I get a chance.

**Comment by 23tux** [comment]
Is there any news on this?

**Comment by magicguitarist** [comment]
The most recent commits should make sadd return the correct response directly, in the same way redis-rb does (by checking arg type)

**Comment by magicguitarist** [comment]
> Will this PR be merged and will there be a new release?

Not sure, might need a review from @caius 🙂

**Comment by McRip** [comment]
Please merge this and release a new version.

**Comment by 23tux** [comment]
I don't want to be pushy, but it's over a year since this fix has been proposed and we are using @magicguitarist solution for quiet a while now in our test suite. So to me, this looks good.

Is there any chance, that a new release with this fix is coming soon?

**Comment by 23tux** [comment]
Is there news on this? Did @caius get a chance to review the PR?

**Comment by 23tux** [comment]
So I guess this project is dead then :(

**Comment by McRip** [comment]
It's not 🎉

**Comment by 23tux** [comment]
Alas, we already switched to MockRedis and I also found a solution to keep a similar behaviour as FakeRedis, e.g. using `Redis.new` in your codebase without worrying about your tests: https://github.com/sds/mock_redis/issues/249#issuecomment-1511280937

**Pull request merged**
