### PR TITLE
Pub/Sub

### PR DESCRIPTION
**Pull request by carsonreinke**
https://github.com/guilleiguaran/fakeredis/issues/29

Here is a start to pubsub.  The subscribe/psubscribe does not block on purpose.  Tests are weak, some aspects are hard to test based on this is setup with `redis-rb`.

### CODE REVIEW

**Comment by syndbg** [comment]
Any progress on this? It's a really useful functionality that will be a benefit for us all :smiley:

**Comment by carsonreinke** [comment]
I am ready to make any adjustments as needed.  The Travis failure is unrelated.  Let me add some simple tests for [p]unsubscribe

**Comment by guilleiguaran** [comment]
@carsonreinke can you rebase this, please?

If TravisCI failures are unrelated I'll merge this :smiley:

**Comment by carsonreinke** [comment]
Who knows what those Travis failures are about.

**Comment by syndbg** [comment]
The travis errors:

```
Libraries missing for ruby-head: libtcl8.5.so.0,libtk8.5.so.0. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, stopping installation.
The command "rvm install ruby-head --binary" failed and exited with 1 during .
```


Looks like an issue in Travis.

**Pull request merged**
